From alpine:3.15.1 as builder
ENV SPARK_URL="https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1.tgz"
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.15/community' >> /etc/apk/repositories 
RUN cd /opt && wget ${SPARK_URL} && tar -zxf spark-3.2.1.tgz

RUN apk update && apk add maven wget bash

RUN cd /opt/spark-3.2.1 && MAVEN_OPTS="-Xss256m -Xmx25g -XX:ReservedCodeCacheSize=2g" ./dev/make-distribution.sh --name ignalina-spark --pip --tgz -Dhadoop.version=3.3.1 -DskipTests
FROM bitnami/spark:3.3.1
# Below follows Bitnami's instruktions
USER root
COPY spark-default .
COPY --from=builder /opt/spark-3.2.1/ignalina-spark-hadoop3.3.1.tgz /home/app
RUN rm -r /opt/bitnami/spark/jars && \
    echo insecure >> ~/.curlrc && \
    tar /home/app/ignalina-spark-hadoop3.3.1.tgz --extract --gzip --strip=1 --directory /opt/bitnami/spark/ spark-3.2.1-hadoop-3.3.1-bin/jars  \
    cat spark-default >> /opt/bitnami/spark/conf/spark-defaults.conf
#    cat spark-default
USER 1001
